<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html lang="en">

<body>
    <h1>Hello ${name} !</h1>

    <spring:url value="/greeting.html?name=${name}" htmlEscape="true" var="springUrl"  />
    <c:url value="/greeting.html?name=${name}" var="url" />

    <p><a href="${springUrl}">URL generated by Spring</a></p>
    <p><a href="${url}">URL generated by JSTL</a></p>
</body>

</html>